### ISSUE TITLE
Feature: Intake mechanism

### ISSUE THREAD

**Issue by numerator** [FRC1076/2022-Competition#7]
## Description
Simple shooter + double solenoid.
piston extends at beginning of auton and stays there forever.
(for testing: piston extends when operator left bumper is pressed, retracts when pressed again)

operator left trigger runs intake motor (at pre-determined speed, e.g., 50%) to suck balls in

**Comment by 1076software** [comment]
Tested on a testbed. Demonstrated making the motor spin and piston toggle.
